defmodule Textur.Repo.Migrations.CreateText do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:texts, primary_key: false) do
      add :created_at, :utc_datetime_usec, null: false
      add :private_password, :text
      add :private, :boolean, null: false
      add :password, :text, null: false
      add :body, :text, null: false
      add :title, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:texts)
  end
end