defmodule Textur.Repo.Migrations.UpdateTextsFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:texts) do
      remove :public

      add :private, :boolean, default: false, null: false
      add :private_password, :text
    end
  end

  def down do
    alter table(:texts) do
      remove :private_password
      remove :private

      add :public, :boolean, null: false
    end
  end
end
